// packages/convex/src/svelte/widgets/SubscriptionIntervalSelector.svelte
<!--
  @component
  Renders the billing interval selector control.

  Automatically hides when only one interval is available for the active group.
  Typically placed inside `Subscription.Root` with `intervalSelector="external"`.
-->
<script lang="ts">
  import { getContext } from "svelte";
  import IntervalSelector from "../primitives/IntervalSelector.svelte";
  import type { RecurringCycle, SupportedRecurringCycle } from "../../core/types.js";
  import {
    SUBSCRIPTION_CONTEXT_KEY,
    type SubscriptionContextValue,
  } from "./subscriptionContext.js";

  interface Props {
    /** Available billing cycles. Defaults to cycles available in the active root group. */
    cycles?: RecurringCycle[];
    /** Controlled selected cycle. Defaults to the root's selected cycle. */
    value?: RecurringCycle;
    /** Called when the user selects a cycle. Defaults to updating the root context. */
    onValueChange?: (cycle: RecurringCycle) => void;
    /** Optional badges shown next to billing interval labels. Defaults to root badges. */
    cycleBadges?: Partial<Record<SupportedRecurringCycle, string>>;
    /** Wrapper CSS class. */
    class?: string;
  }

  let {
    cycles,
    value,
    onValueChange,
    cycleBadges,
    class: className = "",
  }: Props = $props();

  const rootContext = getContext<SubscriptionContextValue | undefined>(
    SUBSCRIPTION_CONTEXT_KEY,
  );
  const resolvedCycles = $derived(cycles ?? rootContext?.availableCycles() ?? []);
  const requestedValue = $derived(
    value ?? rootContext?.getSelectedCycle() ?? resolvedCycles[0],
  );
  const resolvedValue = $derived(
    requestedValue && resolvedCycles.includes(requestedValue)
      ? requestedValue
      : resolvedCycles[0],
  );
  // Merge per cycle rather than replacing the root's map wholesale: supplying a
  // badge for one interval must not silently drop the badges for the others.
  // The React component does the same, so the prop behaves identically on both.
  const resolvedBadges = $derived.by(() => {
    const merged: Partial<Record<SupportedRecurringCycle, string>> = {};
    for (const cycle of resolvedCycles) {
      if (cycle === "custom") continue;
      const badge = cycleBadges?.[cycle] ?? rootContext?.getCycleBadge(cycle);
      if (badge) merged[cycle] = badge;
    }
    return merged;
  });
  const handleValueChange = (cycle: RecurringCycle) => {
    if (onValueChange) {
      onValueChange(cycle);
      return;
    }
    rootContext?.setCycle(cycle);
  };
</script>

<IntervalSelector
  cycles={resolvedCycles}
  value={resolvedValue}
  onValueChange={handleValueChange}
  cycleBadges={resolvedBadges}
  unstyled={rootContext?.getUnstyled() ?? false}
  labels={rootContext?.getLabels() ?? undefined}
  class={className}
/>

// packages/integrations/convex/src/react/widgets/SubscriptionIntervalSelector.tsx
import { useContext } from "react";
import { IntervalSelector } from "../primitives/IntervalSelector.js";
import type {
  RecurringCycle,
  SupportedRecurringCycle,
} from "../../core/types.js";
import { SubscriptionContext } from "./subscriptionContext.js";

/**
 * Renders the billing interval selector control.
 *
 * Automatically hides when only one interval is available for the active group.
 * Typically placed inside `Subscription.Root` with `intervalSelector="external"`.
 *
 * @example
 * ```tsx
 * <Subscription.Root intervalSelector="external">
 *   <Subscription.IntervalSelector className="interval-control" />
 * </Subscription.Root>
 * ```
 */
export const SubscriptionIntervalSelector = ({
  cycles,
  value,
  onValueChange,
  cycleBadges,
  className = "",
}: {
  cycles?: RecurringCycle[];
  value?: RecurringCycle;
  onValueChange?: (cycle: RecurringCycle) => void;
  cycleBadges?: Partial<Record<SupportedRecurringCycle, string>>;
  className?: string;
}) => {
  const rootContext = useContext(SubscriptionContext);
  const resolvedCycles = cycles ?? rootContext?.availableCycles ?? [];
  const requestedValue =
    value ?? rootContext?.selectedCycle ?? resolvedCycles[0];
  const resolvedValue =
    requestedValue && resolvedCycles.includes(requestedValue)
      ? requestedValue
      : resolvedCycles[0];

  // Merge per cycle rather than replacing the root's map wholesale: supplying a
  // badge for one interval must not silently drop the badges for the others.
  // Matches the Svelte component so the same prop renders the same badges on
  // both surfaces.
  const resolvedBadges: Partial<Record<SupportedRecurringCycle, string>> = {};
  for (const cycle of resolvedCycles) {
    if (cycle === "custom") continue;
    const badge = cycleBadges?.[cycle] ?? rootContext?.cycleBadges?.[cycle];
    if (badge) resolvedBadges[cycle] = badge;
  }

  return (
    <IntervalSelector
      cycles={resolvedCycles}
      value={resolvedValue}
      onValueChange={onValueChange ?? rootContext?.setCycle}
      cycleBadges={resolvedBadges}
      unstyled={rootContext?.unstyled ?? false}
      labels={rootContext?.labels}
      className={className}
    />
  );
};
