// packages/convex/src/react/primitives/NumberInput.tsx
import type { ChangeEvent } from "react";
import { defaultBillingLabels } from "../../core/i18n.js";

/**
 * Stepper input used by `Subscription.UnitPicker`.
 *
 * Exported so a replacement unit control can match the built-in styling.
 */
export const NumberInput = ({
  value = 1,
  min = Number.NEGATIVE_INFINITY,
  max = Number.POSITIVE_INFINITY,
  step = 1,
  compact = false,
  disabled = false,
  className = "",
  decreaseLabel = defaultBillingLabels.accessibility.decreaseValue,
  increaseLabel = defaultBillingLabels.accessibility.increaseValue,
  onValueChange,
}: {
  value?: number;
  min?: number;
  max?: number;
  step?: number;
  compact?: boolean;
  disabled?: boolean;
  className?: string;
  decreaseLabel?: string;
  increaseLabel?: string;
  onValueChange?: (value: number) => void;
}) => {
  const clamp = (candidate: number) => Math.min(max, Math.max(min, candidate));

  const setValue = (candidate: number) => {
    const next = clamp(candidate);
    onValueChange?.(next);
  };

  const decrement = () => setValue((value ?? 0) - step);
  const increment = () => setValue((value ?? 0) + step);

  const handleInput = (e: ChangeEvent<HTMLInputElement>) => {
    const parsed = Number(e.currentTarget.value);
    if (!Number.isFinite(parsed)) return;
    setValue(parsed);
  };

  return (
    <div className={`number-input ${className}`}>
      <button
        type="button"
        aria-label={decreaseLabel}
        disabled={disabled}
        className="icon-button-sm"
        onClick={decrement}
      >
        <svg
          aria-hidden="true"
          viewBox="0 0 256 256"
          fill="currentColor"
          className="h-4 w-4 text-foreground-on-tonal"
        >
          <path d="M216,128a12,12,0,0,1-12,12H52a12,12,0,0,1,0-24H204A12,12,0,0,1,216,128Z" />
        </svg>
      </button>

      <input
        type="number"
        className={`input-ghost ${compact ? "number-input-value-compact" : "number-input-value"} max-w-12 input-no-spinner`}
        value={value}
        disabled={disabled}
        onChange={handleInput}
      />

      <button
        type="button"
        aria-label={increaseLabel}
        disabled={disabled}
        className="icon-button-sm"
        onClick={increment}
      >
        <svg
          aria-hidden="true"
          viewBox="0 0 256 256"
          fill="currentColor"
          className="h-4 w-4 text-foreground-on-tonal"
        >
          <path d="M216,128a12,12,0,0,1-12,12H140v64a12,12,0,0,1-24,0V140H52a12,12,0,0,1,0-24h64V52a12,12,0,0,1,24,0v64h64A12,12,0,0,1,216,128Z" />
        </svg>
      </button>
    </div>
  );
};

// packages/convex/src/svelte/primitives/NumberInput.svelte
<!--
  @component
  Stepper input used by `Subscription.UnitPicker`.

  Exported so a replacement unit control can match the built-in styling.
-->
<script lang="ts">
  import { defaultBillingLabels } from "../../core/i18n.js";

  interface Props {
    value?: number;
    min?: number;
    max?: number;
    step?: number;
    compact?: boolean;
    disabled?: boolean;
    className?: string;
    decreaseLabel?: string;
    increaseLabel?: string;
    onValueChange?: (value: number) => void | Promise<void>;
  }

  let {
    value = 1,
    min = Number.NEGATIVE_INFINITY,
    max = Number.POSITIVE_INFINITY,
    step = 1,
    compact = false,
    disabled = false,
    className = "",
    decreaseLabel = defaultBillingLabels.accessibility.decreaseValue,
    increaseLabel = defaultBillingLabels.accessibility.increaseValue,
    onValueChange,
  }: Props = $props();

  const clamp = (candidate: number) => Math.min(max, Math.max(min, candidate));

  const setValue = (candidate: number) => {
    const next = clamp(candidate);
    onValueChange?.(next);
  };

  const decrement = () => setValue((value ?? 0) - step);
  const increment = () => setValue((value ?? 0) + step);
</script>

<div class={`number-input ${className}`}>
  <button
    type="button"
    aria-label={decreaseLabel}
    {disabled}
    class="icon-button-sm"
    onclick={decrement}
  >
    <svg aria-hidden="true" viewBox="0 0 256 256" fill="currentColor" class="h-4 w-4 text-foreground-on-tonal">
      <path d="M216,128a12,12,0,0,1-12,12H52a12,12,0,0,1,0-24H204A12,12,0,0,1,216,128Z" />
    </svg>
  </button>

  <input
    type="number"
    class={`input-ghost ${compact ? "number-input-value-compact" : "number-input-value"} max-w-12 input-no-spinner`}
    value={value}
    {disabled}
    oninput={(event) => {
      const parsed = Number((event.currentTarget as HTMLInputElement).value);
      if (!Number.isFinite(parsed)) return;
      setValue(parsed);
    }}
  />

  <button
    type="button"
    aria-label={increaseLabel}
    {disabled}
    class="icon-button-sm"
    onclick={increment}
  >
    <svg aria-hidden="true" viewBox="0 0 256 256" fill="currentColor" class="h-4 w-4 text-foreground-on-tonal">
      <path d="M216,128a12,12,0,0,1-12,12H140v64a12,12,0,0,1-24,0V140H52a12,12,0,0,1,0-24h64V52a12,12,0,0,1,24,0v64h64A12,12,0,0,1,216,128Z" />
    </svg>
  </button>
</div>
