// packages/convex/src/react/primitives/PaymentWarningBanner.tsx
import { useMemo } from "react";
import type { PaymentSnapshot } from "../../core/types.js";
import { defaultBillingLabels, type BillingLabels } from "../../core/i18n.js";

/**
 * Warning banner for a pending, refunded, or partially refunded payment.
 */
export const PaymentWarningBanner = ({
  payment,
  className = "",
  labels = defaultBillingLabels,
}: {
  payment?: PaymentSnapshot | null;
  className?: string;
  labels?: BillingLabels;
}) => {
  const activePayment = payment ?? null;

  const message = useMemo(() => {
    if (!activePayment || activePayment.status === "paid") return null;
    if (activePayment.status === "pending")
      return labels.paymentWarning.pending;
    if (activePayment.status === "partially_refunded")
      return labels.paymentWarning.partiallyRefunded;
    return labels.paymentWarning.refunded;
  }, [activePayment, labels]);

  if (!message) return null;

  return (
    <div
      className={`rounded-lg border border-rose-300 bg-rose-50 px-4 py-3 text-sm text-rose-900 dark:border-rose-800 dark:bg-rose-950/40 dark:text-rose-200 ${className}`}
    >
      {message}
    </div>
  );
};

// packages/convex/src/svelte/primitives/PaymentWarningBanner.svelte
<!--
  @component
  Warning banner for a pending, refunded, or partially refunded payment.
-->
<script lang="ts">
  /* global $props, $derived */
  import type { PaymentSnapshot } from "../../core/types.js";
  import {
    defaultBillingLabels,
    type BillingLabels,
  } from "../../core/i18n.js";

  interface Props {
    payment?: PaymentSnapshot | null;
    className?: string;
    labels?: BillingLabels;
  }

  let {
    payment = null,
    className = "",
    labels = defaultBillingLabels,
  }: Props = $props();

  const activePayment = $derived(payment ?? null);
  const show = $derived(activePayment != null && activePayment.status !== "paid");
  const message = $derived(
    activePayment?.status === "pending"
      ? labels.paymentWarning.pending
      : activePayment?.status === "partially_refunded"
        ? labels.paymentWarning.partiallyRefunded
        : labels.paymentWarning.refunded,
  );
</script>

{#if show}
  <div
    class={`rounded-lg border border-rose-300 bg-rose-50 px-4 py-3 text-sm text-rose-900 dark:border-rose-800 dark:bg-rose-950/40 dark:text-rose-200 ${className}`}
  >
    {message}
  </div>
{/if}
