// packages/integrations/convex/src/svelte/CreemConvexProvider.svelte
<!--
  @component
  Context boundary every connected widget reads.

  Render it around any `Subscription`, `Product`, `BillingPortal`,
  `BillingHistory`, or `Credits` widget and pass the connected API once; widgets
  no longer take `api` props themselves.

  `createCreemReact` / `createCreemSvelte` return a spreadable binding, so
  `<CreemConvexProvider {...billing}>` wires catalog, API, and defaults together.
-->
<script lang="ts">
  import { setContext, type Snippet } from "svelte";
  import type { PlanCatalog, RecurringCycle } from "../core/types.js";
  import type { BillingI18n } from "../core/i18n.js";
  import {
    CREEM_CONVEX_CONTEXT_KEY,
    type CreemConvexContextValue,
  } from "./creemConvexContext.js";
  import type {
    BillingPermissions,
    CheckoutIntent,
    ConnectedBillingApi,
    PlanChangeIntent,
  } from "./widgets/types.js";

  interface Props {
    /** Connected Convex function references used by all billing widgets below this provider. */
    api: ConnectedBillingApi;
    /** Optional app-owned billing catalog used to resolve plan IDs, labels, product IDs, and limits. */
    catalog?: PlanCatalog;
    /** Default billing cycle for subscription widgets when no local cycle is selected. */
    defaultCycle?: RecurringCycle;
    /** UI permission flags. These only hide/disable client UI; enforce authorization in Convex functions. */
    permissions?: BillingPermissions;
    /** Optional guard that can block checkout before redirecting to Creem. */
    onBeforeCheckout?: (intent: CheckoutIntent) => Promise<boolean> | boolean;
    /** Optional guard that can block paid plan switches and unit updates. */
    onBeforePlanChange?: (
      intent: PlanChangeIntent,
    ) => Promise<boolean> | boolean;
    /** Optional guard that can block activating an app-owned plan. */
    onBeforePlanActivation?: (intent: {
      planId: string;
    }) => Promise<boolean> | boolean;
    /** Locale, labels, and formatting overrides for widgets below this provider. */
    i18n?: BillingI18n;
    /** Billing UI rendered inside the configured provider context. */
    children?: Snippet;
  }

  let {
    api,
    catalog = undefined,
    defaultCycle = undefined,
    permissions = undefined,
    onBeforeCheckout = undefined,
    onBeforePlanChange = undefined,
    onBeforePlanActivation = undefined,
    i18n = undefined,
    children,
  }: Props = $props();

  const contextValue: CreemConvexContextValue = {
    get api() {
      return api;
    },
    get catalog() {
      return catalog;
    },
    get defaultCycle() {
      return defaultCycle;
    },
    get permissions() {
      return permissions;
    },
    get onBeforeCheckout() {
      return onBeforeCheckout;
    },
    get onBeforePlanChange() {
      return onBeforePlanChange;
    },
    get onBeforePlanActivation() {
      return onBeforePlanActivation;
    },
    get i18n() {
      return i18n;
    },
  };

  setContext(CREEM_CONVEX_CONTEXT_KEY, contextValue);
</script>

{@render children?.()}

// packages/convex/src/react/CreemConvexProvider.tsx
/* eslint-disable react-refresh/only-export-components */
import {
  createContext,
  useContext,
  useMemo,
  type PropsWithChildren,
} from "react";
import type { PlanCatalog, RecurringCycle } from "../core/types.js";
import type { BillingI18n } from "../core/i18n.js";
import type {
  BillingPermissions,
  CheckoutIntent,
  ConnectedBillingApi,
  PlanChangeIntent,
} from "./widgets/types.js";

/**
 * The value `CreemConvexProvider` accepts and every connected widget reads.
 */
export interface CreemConvexContextValue {
  /**
   * Connected Convex function references, built with
   * `connectCreemApi(api.billing)`; the fields you supply decide which controls
   * the widgets render.
   */
  api: ConnectedBillingApi;
  /**
   * App-owned billing catalog used by the subscription widgets and by
   * `plansOf`.
   */
  catalog?: PlanCatalog;
  /**
   * Billing cycle subscription widgets start on when they do not set their own.
   */
  defaultCycle?: RecurringCycle;
  /**
   * Provider-level UI permission flags; these hide controls only, so enforce
   * real authorization in your Convex functions.
   */
  permissions?: BillingPermissions;
  /**
   * Runs before any checkout starts; return `false` to abort, for example to
   * gate on sign-in or accepted terms.
   */
  onBeforeCheckout?: (intent: CheckoutIntent) => Promise<boolean> | boolean;
  /**
   * Runs before a paid plan switch or unit update; return `false` to abort.
   */
  onBeforePlanChange?: (intent: PlanChangeIntent) => Promise<boolean> | boolean;
  /**
   * Runs before an app-owned plan (free, no-card trial) is activated; return
   * `false` to abort.
   */
  onBeforePlanActivation?: (intent: {
    planId: string;
  }) => Promise<boolean> | boolean;
  /**
   * Locale, label, date, and currency formatter overrides.
   */
  i18n?: BillingI18n;
}

const CreemConvexContext = createContext<CreemConvexContextValue | null>(null);

/**
 * Reads the `CreemConvexProvider` context: billing model, loading and error
 * state, and the checkout, plan, and cancellation actions.
 *
 * @throws When called outside a `CreemConvexProvider`.
 */
export const useCreemConvex = () => useContext(CreemConvexContext);

export const requireCreemConvexApi = (
  componentName: string,
  provider: CreemConvexContextValue | null,
) => {
  const resolvedApi = provider?.api;
  if (!resolvedApi) {
    throw new Error(
      `${componentName} must be rendered inside <CreemConvexProvider>.`,
    );
  }
  return resolvedApi;
};

/**
 * Context boundary every connected widget reads.
 *
 * Render it around any `Subscription`, `Product`, `BillingPortal`,
 * `BillingHistory`, or `Credits` widget and pass the connected API once; widgets
 * no longer take `api` props themselves.
 *
 * `createCreemReact` / `createCreemSvelte` return a spreadable binding, so
 * `<CreemConvexProvider {...billing}>` wires catalog, API, and defaults together.
 */
export const CreemConvexProvider = ({
  api,
  catalog,
  defaultCycle,
  permissions,
  onBeforeCheckout,
  onBeforePlanChange,
  onBeforePlanActivation,
  i18n,
  children,
}: PropsWithChildren<CreemConvexContextValue>) => {
  const value = useMemo(
    () => ({
      api,
      catalog,
      defaultCycle,
      permissions,
      onBeforeCheckout,
      onBeforePlanChange,
      onBeforePlanActivation,
      i18n,
    }),
    [
      api,
      catalog,
      defaultCycle,
      permissions,
      onBeforeCheckout,
      onBeforePlanChange,
      onBeforePlanActivation,
      i18n,
    ],
  );

  return (
    <CreemConvexContext.Provider value={value}>
      {children}
    </CreemConvexContext.Provider>
  );
};
